import {HomePageSelectors} from "../../Fixtures/Selectors/HomePageSelectors";
import {HomePageMethods} from "../../Fixtures/Methods/HomePageMethods";
import {SignInMethods} from "../../Fixtures/Methods/SignInMethods";
import {SignInGenerators} from "../../Fixtures/Generators/SignInGenerators";
import { Redirects } from "../../Fixtures/Models/HomePageModels";

describe('Home Page', () => {
    context('Positive cases', () => {
        beforeEach(() => {
            cy.session('user4004', () => {
                cy.visit('/')
                SignInMethods.SignIn(SignInGenerators.User4004.username, SignInGenerators.User4004.password)
            })
            cy.visit('/')
        })

        it('Should check burger button work', () => {
            HomePageSelectors.burgerButton().click()
            HomePageSelectors.sidebarMenu().should('not.be.visible')
        })

        it('Should check payment modal opening', () => {
            HomePageSelectors.paymentsButton().click()
            HomePageSelectors.paymentsModal().should('be.visible')
            HomePageSelectors.payButton().should('be.disabled')
            HomePageSelectors.paymentPrice().should('be.visible')
            HomePageSelectors.paymentMethodButton().click()
            HomePageSelectors.payButton().should('be.enabled')
            HomePageSelectors.paymentModalCloseButton().click()
            HomePageSelectors.paymentsModal().should('not.exist')
        })
        it('Should check language change', () => {
            HomePageSelectors.headerText().should('contain.text', 'Գլխավոր')
            HomePageSelectors.languageButton().click()
            HomePageSelectors.languageDropdown().should('be.visible')
            HomePageSelectors.languageDropdownOptions(1).click()
            HomePageSelectors.languageDropdown().should('not.exist')
            HomePageSelectors.headerText().should('contain.text', 'Home')
            HomePageSelectors.languageButton().click()
            HomePageSelectors.languageDropdown().should('be.visible')
            HomePageSelectors.languageDropdownOptions(2).click()
            HomePageSelectors.languageDropdown().should('not.exist')
            HomePageSelectors.headerText().should('contain.text', 'Главная')
        })
        it('Should check profile button work', () => {
            HomePageSelectors.profileButton().click()
            HomePageSelectors.profileSettingsButton().should('be.visible')
            HomePageSelectors.logOutButton().should('be.visible')
            HomePageSelectors.profileButton().click()
            cy.wait(1000)
            HomePageSelectors.profileModal().should('not.exist')
        })
        it('Should check sidebar Lists correct redirects', () => {
            HomePageSelectors.sidebarProductsButton().click()
            cy.url().should('include', Redirects.products)
            HomePageSelectors.sidebarListsButton().click()
            HomePageSelectors.sidebarListsUnitOfMeasurementsButton().click()
            cy.url().should('include', Redirects.unitOfMeasurements)
            HomePageSelectors.sidebarListsCategoriesButton().click()
            cy.url().should('include', Redirects.categoryTypes)
            HomePageSelectors.sidebarListsPaymentListButton().click()
            cy.url().should('include', Redirects.listOfPayments)
            HomePageSelectors.sidebarListsWarehousesButton().click()
            cy.url().should('include', Redirects.listOfWarehouses)
            HomePageSelectors.sidebarListsCashRegisterTypesButton().click()
            cy.url().should('include', Redirects.cashRegisterTypes)
            HomePageSelectors.sidebarListsProductColorButton().click()
            cy.url().should('include', Redirects.productColor)
            HomePageSelectors.sidebarListsSizeButton().click()
            cy.url().should('include', Redirects.size)
            HomePageSelectors.sidebarListsCurrenciesButton().click()
            cy.url().should('include', Redirects.currencies)
            HomePageSelectors.sidebarListsDiscountsButton().click()
            cy.url().should('include', Redirects.discounts)
            HomePageSelectors.sidebarListsPartnersButton().click()
            cy.url().should('include', Redirects.partners)
        })
        it('Should check sidebar documents correct redirects', () => {
            HomePageSelectors.sidebarInvoicesButton().click()
            HomePageSelectors.sidebarInvoicesListOfInvoicesButton().click()
            cy.url().should('include', Redirects.listOfInvoices)
            HomePageSelectors.sidebarInvoicesPurchaseOrderButton().click()
            cy.url().should('include', Redirects.purchaseOrder)
            HomePageSelectors.sidebarInvoicesWithdrawalButton().click()
            cy.url().should('include', Redirects.withdrawalInvoice)
            HomePageSelectors.sidebarInvoicesWriteOffButton().click()
            cy.url().should('include', Redirects.writeOff)
            HomePageSelectors.sidebarInvoicesInternalTransferButton().click()
            cy.url().should('include', Redirects.internalTransfer)
            HomePageSelectors.sidebarInvoicesReturnToProviderButton().click()
            cy.url().should('include', Redirects.returnToProvider)
            HomePageSelectors.sidebarInvoicesBuyerReturnButton().click()
            cy.url().should('include', Redirects.buyerReturn)
            HomePageSelectors.sidebarCashOrderButton().click()
            HomePageSelectors.sidebarCashOrderListOfCashOrdersButton().click()
            cy.url().should('include', Redirects.listOfCashOrders)
            HomePageSelectors.sidebarCashOrderCreateCashOrderButton().click()
            cy.url().should('include', Redirects.createCashOrder)
            HomePageSelectors.sidebarActsButton().click()
            HomePageSelectors.sidebarActsListOfActsButton().click()
            cy.url().should('include', Redirects.listOfActs)
            HomePageSelectors.sidebarCreateAnActButton().click()
            cy.url().should('include', Redirects.createAct)
            HomePageSelectors.sidebarInventoryButton().click()
            HomePageSelectors.sidebarInventoryListOfInventoriesButton().click()
            cy.url().should('include', Redirects.listOfInventories)
            HomePageSelectors.sidebarInventoryCreateInventoryButton().click()
            cy.url().should('include', Redirects.createInventory)
        })
        it('Should check Sales Reports and Vendors redirects', () => {
            HomePageSelectors.sidebarSalesButton().click()
            HomePageSelectors.sidebarSalesListSalesButton().click()
            cy.url().should('include', Redirects.listOfSales)
            HomePageSelectors.sidebarSalesInvoiceButton().click()
            cy.url().should('include', Redirects.createSale)
            HomePageSelectors.sidebarReportsButton().click()
            HomePageSelectors.sidebarReportsChecksButton().click()
            cy.url().should('include', Redirects.checks)
            HomePageSelectors.sidebarReportsImplementationReportButton().click()
            cy.url().should('include', Redirects.implementationReport)
            HomePageSelectors.sidebarReportsCounterpartiesButton().click()
            cy.url().should('include', Redirects.counterparties)
            HomePageSelectors.sidebarReportsRevenuesButton().click()
            cy.url().should('include', Redirects.revenues)
            HomePageSelectors.sidebarReportsFinancesButton().click()
            cy.url().should('include', Redirects.finances)
            HomePageSelectors.sidebarReportsProductReportsButton().click()
            cy.url().should('include', Redirects.productReports)
            HomePageSelectors.sidebarVendorsButton().click()
            HomePageSelectors.sidebarVendorsPurchasesButton().click()
            cy.url().should('include', Redirects.vendorsPurchases)
            HomePageSelectors.sidebarVendorsPurchaseOrderButton().click()
            cy.url().should('include', Redirects.vendorsPurchaseOrder)
            HomePageSelectors.sidebarVendorsExpenseButton().click()
            cy.url().should('include', Redirects.vendorsExpense)
        })
        it('Should check Settings redirects', () => {
            HomePageSelectors.profileButton().click()
            HomePageSelectors.profileSettingsButton().click()
            cy.url().should('include', Redirects.settings)
        })
    })
})